# Generated by Django 5.2.4 on 2025-08-01 16:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_education'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='EducationModel',
        ),
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserProfileModel',
        ),
    ]
