# Generated by Django 5.2.4 on 2025-08-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_education_educationmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducationModel',
            new_name='AddEducationModel',
        ),
    ]
