# Generated by Django 5.2.4 on 2025-08-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_addexperiencemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='bio',
            field=models.CharField(default='bio for You', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='picture',
            field=models.ImageField(default='user_profile/profile.png', upload_to='user_profile'),
        ),
    ]
