# Generated by Django 5.2.4 on 2025-08-02 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_addexperiencemodel'),
        ('blog', '0002_commetmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commetmodel',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofilemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofilemodel'),
            preserve_default=False,
        ),
    ]
