# Generated by Django 5.2.4 on 2025-08-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofilemodel_bio_and_more'),
        ('blog', '0003_commetmodel_author_postmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='dislike',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_dislike', to='accounts.userprofilemodel'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_like', to='accounts.userprofilemodel'),
        ),
    ]
